global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app_food'
    static_configs:
      - targets: [ 'app_food:80' ]
    # metrics_path: /metrics/delivery
  - job_name: 'app_order'
    static_configs:
      - targets: [ 'app_order:81' ]
    # metrics_path: /metrics/printings
  - job_name: 'postgres_food'
    static_configs:
      - targets: [ 'postgres_food:5432' ]
      # metrics_path: /metrics/printings
  - job_name: 'postgres_order'
    static_configs:
      - targets: [ 'postgres_food:5433' ]
      # metrics_path: /metrics/printings